version: '3.8'
services:
  python-backend:
    image: visenseio/python-backend:${VERSION:-latest}
    build:
      context: python-backend/
    env_file: .env
    depends_on:
      - db
      - fastapi
    networks:
      - visense-network
    environment:
      - ENABLE_DEMO_DATA=true
    ports:
      - '50505:50505'
#  react:
#    tty: true
#    build:
#      context: react-frontend
#    environment:
#      - REACT_APP_BACKEND_HOST=http://localhost:3001
#      - REACT_APP_WEBSOCKET_PATH=/socket.io
#      - REACT_APP_MINIO_URL=http://localhost:9006
#      - REACT_APP_LIVESTREAM_URL=http://localhost:8080
#    networks:
#      - visense-network
#    logging:
#      driver: journald
#      options:
#        tag: "{{.Name}}"
volumes:
  pgdata:
networks:
  visense-network:
    name: visense-network
