version: '3.8'
services:
  python-backend:
    image: visenseio/python-backend:${VERSION:-latest}
    build:
      context: python-backend/
    env_file: .env
    # depends_on:
    #   - db
    #   - fastapi
    networks:
      - visense-network
    environment:
      - ENABLE_DEMO_DATA=true
    ports:
      - '50505:50505'
  web:
    build:
      context: .
      dockerfile: react-frontend/Dockerfile
      cache_from:
        - eu.gcr.io/tmrow-152415/electricitymap_web:production
        - eu.gcr.io/tmrow-152415/electricitymap_web:staging
        - eu.gcr.io/tmrow-152415/electricitymap_web:latest
    image: eu.gcr.io/tmrow-152415/electricitymap_web:latest
    command: npm run server-dev
    environment:
      - NODE_ENV=development
    ports: ['8000:8000']
    volumes:
      - './react-frontend/config:/home/config'
      - './react-frontend/.eslintrc:/home/src/electricitymap/contrib/web/.eslintrc'
      - './react-frontend/geo:/home/src/electricitymap/contrib/web/geo'
      - './react-frontend/public/locales:/home/src/electricitymap/contrib/web/public/locales'
      - './react-frontend/locales-config.json:/home/src/electricitymap/contrib/web/locales-config.json'
      - './react-frontend/package.json:/home/src/electricitymap/contrib/web/package.json'
      - './react-frontend/public:/home/src/electricitymap/contrib/web/public'
      - './react-frontend/server.js:/home/src/electricitymap/contrib/web/server.js'
      - './react-frontend/src:/home/src/electricitymap/contrib/web/src'
      - './react-frontend/views:/home/src/electricitymap/contrib/web/views'
      - './react-frontend/webpack.config.js:/home/src/electricitymap/contrib/web/webpack.config.js'
    networks:
      - frontend-network
  web-watch:
    build:
      context: .
      dockerfile: react-frontend/Dockerfile
      cache_from:
        - eu.gcr.io/tmrow-152415/electricitymap_web:production
        - eu.gcr.io/tmrow-152415/electricitymap_web:staging
        - eu.gcr.io/tmrow-152415/electricitymap_web:latest
    image: eu.gcr.io/tmrow-152415/electricitymap_web:latest
    command: npm run watch
    environment:
      - NODE_ENV=development
    volumes:
      - './config:/home/config'
      - './react-frontend/.eslintrc:/home/src/electricitymap/contrib/web/.eslintrc'
      - './react-frontend/geo:/home/src/electricitymap/contrib/web/geo'
      - './react-frontend/public/locales:/home/src/electricitymap/contrib/web/public/locales'
      - './react-frontend/locales-config.json:/home/src/electricitymap/contrib/web/locales-config.json'
      - './react-frontend/package.json:/home/src/electricitymap/contrib/web/package.json'
      - './react-frontend/public:/home/src/electricitymap/contrib/web/public'
      - './react-frontend/server.js:/home/src/electricitymap/contrib/web/server.js'
      - './react-frontend/src:/home/src/electricitymap/contrib/web/src'
      - './react-frontend/views:/home/src/electricitymap/contrib/web/views'
      - './react-frontend/webpack.config.js:/home/src/electricitymap/contrib/web/webpack.config.js'
    networks:
      - frontend-network
volumes:
  pgdata:
networks:
  visense-network:
    name: visense-network
  frontend-network:
    name: frontend-network